'use client'
import {useEffect,useState} from 'react'
const api=process.env.NEXT_PUBLIC_NEURAQ_API||''
export default function Admin(){
 const [token,setToken]=useState(''); const [stories,setStories]=useState<any[]>([]); const [stats,setStats]=useState<any>(null); const [editing,setEditing]=useState<string|null>(null); const [form,setForm]=useState<any>({title:'',summary:'',body:'',status:'draft',featured:false,source_urls:[]}); const [msg,setMsg]=useState('')
 const headers=()=>({'Content-Type':'application/json','X-Admin-Token':token})
 async function load(){if(!token)return;const [a,b]=await Promise.all([fetch(api+'/v1/admin/stories',{headers:headers()}),fetch(api+'/v1/admin/analytics/summary',{headers:headers()})]);if(a.ok)setStories(await a.json());if(b.ok)setStats(await b.json());else setStats({error:'Analytics todavía no disponible'})}
 useEffect(()=>{if(token)load()},[token])
 async function save(){const url=editing?api+'/v1/admin/stories/'+editing:api+'/v1/admin/stories';const method=editing?'PUT':'POST';const r=await fetch(url,{method,headers:headers(),body:JSON.stringify(form)});setMsg(r.ok?(editing?'Publicación actualizada':'Publicación guardada'):'Error al guardar');setEditing(null);setForm({title:'',summary:'',body:'',status:'draft',featured:false,source_urls:[]});load()}
 function edit(s:any){setEditing(s.id);setForm({title:s.title||'',summary:s.summary||'',body:s.body||'',status:s.status||'draft',featured:!!s.featured,source_urls:s.source_urls||[]});window.scrollTo({top:0,behavior:'smooth'})}
 async function remove(id:string){if(!confirm('¿Borrar esta publicación?'))return;await fetch(api+'/v1/admin/stories/'+id,{method:'DELETE',headers:headers()});load()}
 async function feature(id:string,v:boolean){await fetch(api+'/v1/admin/stories/'+id+'/featured',{method:'POST',headers:headers(),body:JSON.stringify({featured:v})});load()}
 return <main className='admin'><header><div className='brand'>Neura<span>Q</span> · Admin</div><a href='/'>Ver sitio</a></header>
 {!token?<section className='login card'><h1>Panel administrativo</h1><p>Ingresá el token de administrador configurado en el backend.</p><input type='password' placeholder='ADMIN_TOKEN' onChange={e=>setToken(e.target.value)}/><button onClick={load}>Entrar</button></section>:
 <><section className='dashboard'><div className='metric'><b>{stats?.live??0}</b><span>En vivo</span></div><div className='metric'><b>{stats?.shares??0}</b><span>Compartidos</span></div><div className='metric'><b>{stories.length}</b><span>Historias</span></div><div className='metric'><b>{stats?.events??0}</b><span>Eventos</span></div></section>
 <section className='card'><h2>{editing?'Editar publicación':'Nueva publicación'}</h2><div className='formgrid'><input placeholder='Título' value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value='draft'>Borrador</option><option value='verified'>Verificada</option><option value='published'>Publicar</option><option value='rejected'>Rechazada</option></select><textarea placeholder='Resumen' value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><textarea className='body' placeholder='Contenido original de la noticia' value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></div><button onClick={save}>{editing?'Actualizar':'Guardar'}</button> {editing?<button onClick={()=>{setEditing(null);setForm({title:'',summary:'',body:'',status:'draft',featured:false,source_urls:[]})}}>Cancelar</button>:null}<p>{msg}</p></section>
 <section className='card'><h2>Publicaciones</h2>{stories.map(s=><article className='row' key={s.id}><div><b>{s.title}</b><small>{s.status} · {s.view_count||0} lecturas {s.featured?' · DESTACADA':''}</small></div><div className='actions'><button onClick={()=>edit(s)}>Editar</button><button onClick={()=>feature(s.id,!s.featured)}>{s.featured?'Quitar destacada':'Destacar'}</button><a href={'/story/'+s.id}>Ver</a><button onClick={()=>remove(s.id)}>Borrar</button></div></article>)}</section>
 <section className='card'><h2>Audiencia y publicidad</h2><div className='stats'><div><h3>Países</h3><pre>{JSON.stringify(stats?.countries||[],null,2)}</pre></div><div><h3>Dispositivos</h3><pre>{JSON.stringify(stats?.devices||[],null,2)}</pre></div><div><h3>Fuentes</h3><pre>{JSON.stringify(stats?.sources||[],null,2)}</pre></div><div><h3>Intereses / artículos</h3><pre>{JSON.stringify(stats?.interests||[],null,2)}</pre></div></div><p>Preparado para GA4 y Google AdSense. La activación real requiere colocar tus IDs y completar la revisión de Google.</p></section></>}
 </main>}
