'use client'
import {useEffect,useState} from 'react'
const api=process.env.NEXT_PUBLIC_NEURAQ_API||'http://localhost:8000'
export default function Admin(){
 const [token,setToken]=useState(''); const [stories,setStories]=useState<any[]>([]); const [stats,setStats]=useState<any>(null); const [form,setForm]=useState<any>({title:'',summary:'',body:'',status:'draft',featured:false,source_urls:[]}); const [msg,setMsg]=useState('')
 const headers=()=>({'Content-Type':'application/json','X-Admin-Token':token})
 async function load(){if(!token)return;const [a,b]=await Promise.all([fetch(api+'/v1/admin/stories',{headers:headers()}),fetch(api+'/v1/admin/analytics/summary',{headers:headers()})]);if(a.ok)setStories(await a.json());if(b.ok)setStats(await b.json());else setStats({error:'Analytics todavía no disponible'})}
 useEffect(()=>{if(token)load()},[token])
 async function save(){const r=await fetch(api+'/v1/admin/stories',{method:'POST',headers:headers(),body:JSON.stringify(form)});setMsg(r.ok?'Publicación guardada':'Error al guardar');load()}
 async function remove(id:string){if(!confirm('¿Borrar esta publicación?'))return;await fetch(api+'/v1/admin/stories/'+id,{method:'DELETE',headers:headers()});load()}
 async function feature(id:string,v:boolean){await fetch(api+'/v1/admin/stories/'+id+'/featured',{method:'POST',headers:headers(),body:JSON.stringify({featured:v})});load()}
 return <main className='admin'><header><div className='brand'>Neura<span>Q</span> · Admin</div><a href='/'>Ver sitio</a></header>
 {!token?<section className='login card'><h1>Panel administrativo</h1><p>Ingresá el token de administrador configurado en el backend.</p><input type='password' placeholder='ADMIN_TOKEN' onChange={e=>setToken(e.target.value)}/><button onClick={load}>Entrar</button></section>:
 <><section className='dashboard'><div className='metric'><b>{stats?.live??0}</b><span>En vivo</span></div><div className='metric'><b>{stats?.shares??0}</b><span>Compartidos</span></div><div className='metric'><b>{stories.length}</b><span>Historias</span></div><div className='metric'><b>{stats?.events??0}</b><span>Eventos</span></div></section>
 <section className='card'><h2>Nueva publicación</h2><div className='formgrid'><input placeholder='Título' value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value='draft'>Borrador</option><option value='verified'>Verificada</option><option value='published'>Publicar</option><option value='rejected'>Rechazada</option></select><textarea placeholder='Resumen' value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><textarea className='body' placeholder='Contenido original de la noticia' value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></div><button onClick={save}>Guardar</button></section>
 <section className='card'><h2>Publicaciones</h2>{stories.map(s=><article className='row' key={s.id}><div><b>{s.title}</b><small>{s.status} · {s.view_count||0} lecturas {s.featured?' · DESTACADA':''}</small></div><div className='actions'><button onClick={()=>feature(s.id,!s.featured)}>{s.featured?'Quitar destacada':'Destacar'}</button><a href={'/story/'+s.id}>Ver</a><button onClick={()=>remove(s.id)}>Borrar</button></div></article>)}</section>
 <section className='card'><h2>Audiencia</h2><div className='stats'><div><h3>Países</h3><pre>{JSON.stringify(stats?.countries||[],null,2)}</pre></div><div><h3>Dispositivos</h3><pre>{JSON.stringify(stats?.devices||[],null,2)}</pre></div><div><h3>Fuentes</h3><pre>{JSON.stringify(stats?.sources||[],null,2)}</pre></div><div><h3>Intereses / artículos</h3><pre>{JSON.stringify(stats?.interests||[],null,2)}</pre></div></div></section>
 <section className='card'><h2>Monetización</h2><p>Configuración preparada para Google AdSense: publisher ID, Auto ads, posiciones superior, inline, lateral y footer. No se activa publicidad hasta cargar y verificar tu cuenta.</p><p>También dejamos el sitio preparado para consentimiento, privacidad, cookies, ads.txt y Analytics.</p></section></>}
 </main>}
