'use client'
import {useEffect,useMemo,useState} from 'react'
type Story={id:string,title:string,summary?:string,published_at?:string,updated_at?:string,category?:string,source_urls?:string[]}
const fallback:Story[]=[
{id:'pobreza-argentina-2026',category:'Economía',title:'La pobreza alcanzó el 32,3% en Argentina durante el primer semestre de 2026',summary:'El dato informado para el primer semestre ubicó la pobreza en 32,3%. NeuraQ presenta el dato con contexto y fuente identificable.',published_at:'2026-09-25',source_urls:['https://www.lanacion.com.ar/']},
{id:'actividad-economica-julio-2026',category:'Economía',title:'La actividad económica registró una caída mensual en julio',summary:'Los datos difundidos sobre el EMAE muestran una contracción mensual en julio. NeuraQ reúne el dato y separa la cifra de las interpretaciones.',published_at:'2026-09-25',source_urls:['https://www.lanacion.com.ar/']},
{id:'riesgo-pais-578',category:'Economía',title:'El riesgo país argentino cerró la jornada en 578 puntos',summary:'El índice de riesgo país fue reportado en 578 puntos al cierre del 24 de septiembre, en una jornada de movimientos en bonos y acciones.',published_at:'2026-09-25',source_urls:['https://www.infobae.com/']},
{id:'ciencia-tecnologia-argentina',category:'Tecnología',title:'Argentina mantiene una agenda de cooperación en ciencia y tecnología',summary:'La Secretaría de Innovación, Ciencia y Tecnología informó actividades vinculadas con supercomputación, inteligencia artificial y cooperación científica.',published_at:'2026-09-24',source_urls:['https://www.argentina.gob.ar/node/3/noticias']},
{id:'argentina-emiratos-comercio',category:'Mundo',title:'Argentina y Emiratos Árabes Unidos difundieron una declaración sobre comercio e inversión',summary:'La Cancillería argentina publicó una declaración conjunta sobre comercio e inversión el 24 de septiembre.',published_at:'2026-09-24',source_urls:['https://www.cancilleria.gob.ar/es/argentinatradenet/noticias']},
{id:'malvinas-negociaciones-2026',category:'Política',title:'La disputa por Malvinas volvió a ocupar espacio en la agenda internacional',summary:'Declaraciones recientes de autoridades argentinas y británicas volvieron a poner el diferendo de soberanía en la agenda internacional. NeuraQ presenta las posiciones atribuidas a sus fuentes.',published_at:'2026-09-24',source_urls:['https://efe.com/noticias/argentina/']},
]
export default function NewsSection({category}:{category?:string}){
 const [stories,setStories]=useState<Story[]>(fallback); const [loading,setLoading]=useState(true); const [query,setQuery]=useState('')
 const api=process.env.NEXT_PUBLIC_NEURAQ_API||''
 useEffect(()=>{if(!api){setLoading(false);return}fetch(api+'/v1/stories?limit=50').then(r=>r.ok?r.json():[]).then(v=>{if(Array.isArray(v)&&v.length)setStories(v)}).catch(()=>{}).finally(()=>setLoading(false))},[api])
 const filtered=useMemo(()=>stories.filter(s=>{const text=(s.title+' '+(s.summary||'')).toLowerCase(); return (!category||s.category?.toLowerCase()===category.toLowerCase())&&(!query||text.includes(query.toLowerCase()))}),[stories,category,query])
 return <section className='news-section'><div className='section-head'><div><span className='eyebrow'>COBERTURA NEURAQ</span><h2>{category||'Últimas historias'}</h2></div><label className='search'><span>⌕</span><input aria-label='Buscar noticias' placeholder='Buscar en NeuraQ…' value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{loading?<div className='empty card'><span className='pulse'></span><h3>Actualizando la redacción</h3><p>Consultando historias verificadas…</p></div>:<div className='news-grid'>{filtered.map((s,i)=><article className={i===0?'news-card featured-card':'news-card'} key={s.id}><div className='card-top'><span>{s.category||'Actualidad'}</span><time>{s.published_at||s.updated_at||'Ahora'}</time></div><h3>{s.title}</h3><p>{s.summary}</p><a className='read' href={'/story/'+encodeURIComponent(s.id)}>Abrir historia <span>↗</span></a></article>)}</div>}</section>
}