'use client'
import {useEffect,useState} from 'react'
const api=process.env.NEXT_PUBLIC_NEURAQ_API||''
const fallback:any={
'pobreza-argentina-2026':{id:'pobreza-argentina-2026',title:'La pobreza alcanzó el 32,3% en Argentina durante el primer semestre de 2026',summary:'El dato informado para el primer semestre ubicó la pobreza en 32,3%. Esta nota presenta el dato de forma contextualizada y con referencia a la fuente original.',body:'El indicador de pobreza informado para el primer semestre de 2026 fue de 32,3%. NeuraQ presenta esta cifra como dato de referencia y evita atribuirle por sí sola causas o consecuencias que no estén verificadas.\n\nFuente: La Nación.',category:'Economía',source_urls:['https://www.lanacion.com.ar/']},
'actividad-economica-julio-2026':{id:'actividad-economica-julio-2026',title:'La actividad económica registró una caída mensual en julio',summary:'Los datos difundidos sobre el EMAE muestran una contracción mensual en julio.',body:'La actividad económica argentina registró una caída mensual en julio según los datos publicados sobre el EMAE. La variación debe leerse junto con la evolución acumulada y los datos sectoriales, evitando extrapolaciones que no surjan de la estadística oficial.\n\nFuente de referencia: La Nación.',category:'Economía',source_urls:['https://www.lanacion.com.ar/']},
'riesgo-pais-578':{id:'riesgo-pais-578',title:'El riesgo país argentino cerró la jornada en 578 puntos',summary:'El índice fue reportado en 578 puntos al cierre del 24 de septiembre.',body:'El riesgo país argentino fue reportado en 578 puntos al cierre de la jornada del 24 de septiembre. La cifra refleja las condiciones de mercado de ese momento y no constituye por sí sola una predicción sobre la evolución futura.\n\nFuente de referencia: Infobae.',category:'Economía',source_urls:['https://www.infobae.com/']},
'ciencia-tecnologia-argentina':{id:'ciencia-tecnologia-argentina',title:'Argentina mantiene una agenda de cooperación en ciencia y tecnología',summary:'La Secretaría de Innovación, Ciencia y Tecnología informó actividades vinculadas con supercomputación e inteligencia artificial.',body:'La agenda oficial reciente incluye cooperación científica, supercomputación e inteligencia artificial. NeuraQ utiliza la publicación institucional como fuente primaria para esta ficha informativa.\n\nFuente: Argentina.gob.ar.',category:'Tecnología',source_urls:['https://www.argentina.gob.ar/node/3/noticias']},
'argentina-emiratos-comercio':{id:'argentina-emiratos-comercio',title:'Argentina y Emiratos Árabes Unidos difundieron una declaración sobre comercio e inversión',summary:'La Cancillería argentina publicó una declaración conjunta el 24 de septiembre.',body:'La Cancillería argentina informó una declaración conjunta sobre comercio e inversión entre Argentina y Emiratos Árabes Unidos. Esta ficha resume el hecho anunciado sin reproducir el documento original.\n\nFuente: Cancillería Argentina.',category:'Mundo',source_urls:['https://www.cancilleria.gob.ar/es/argentinatradenet/noticias']},
'malvinas-negociaciones-2026':{id:'malvinas-negociaciones-2026',title:'La disputa por Malvinas volvió a ocupar espacio en la agenda internacional',summary:'Declaraciones recientes de autoridades argentinas y británicas volvieron a poner el diferendo de soberanía en la agenda internacional.',body:'En septiembre de 2026, declaraciones de autoridades argentinas y británicas volvieron a referirse a la disputa de soberanía sobre las Islas Malvinas. NeuraQ distingue las posiciones atribuidas a cada parte y evita presentar una interpretación política propia como hecho.\n\nFuente de referencia: EFE.',category:'Política',source_urls:['https://efe.com/noticias/argentina/']}
}
type Story={id:string,title:string,summary?:string,body?:string,published_at?:string,updated_at?:string,source_urls?:string[],correction_history?:{reason:string,created_at:string}[]}
function host(url:string){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return 'Fuente'}}
export default function StoryPage(){const [id,setId]=useState('');const [s,setS]=useState<Story|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{const value=new URLSearchParams(window.location.search).get('id')||window.location.pathname.split('/').filter(Boolean).pop()||'';setId(value);if(!value){setLoading(false);return}fetch(api+'/v1/stories/'+encodeURIComponent(value)).then(r=>r.ok?r.json():null).then(v=>setS(v||fallback[value])).catch(()=>setS(fallback[value]||null)).finally(()=>setLoading(false))},[]);if(loading)return <main><div className='empty card'><span className='pulse'></span><h2>Cargando historia…</h2></div></main>;if(!s)return <main><header><a className='brand' href='/'>Neura<span>Q</span></a></header><article className='story'><span className='eyebrow'>NEURAQ · 404</span><h1>Historia no encontrada</h1><p className='lead'>La publicación puede haber sido actualizada, retirada o todavía no estar disponible.</p><a className='primary' href='/'>Volver a noticias</a></article></main>;const jsonLd={'@context':'https://schema.org','@type':'NewsArticle','headline':s.title,'description':s.summary,'datePublished':s.published_at||s.updated_at,'dateModified':s.updated_at,'author':{'@type':'Organization','name':'NeuraQ','url':'https://neuraq.dev.ar'},'publisher':{'@type':'Organization','name':'NeuraQ','url':'https://neuraq.dev.ar'},'mainEntityOfPage':{'@type':'WebPage','@id':'https://neuraq.dev.ar/story/'+id}};return <main><script type='application/ld+json' dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header><a className='brand' href='/'>Neura<span>Q</span></a><nav><a href='/'>Inicio</a><a href='/rss.xml'>RSS</a></nav></header><article className='story'><span className='eyebrow'>NEURAQ · NOTICIA</span><h1>{s.title}</h1>{s.summary?<p className='lead'>{s.summary}</p>:null}<div className='storybody'>{s.body}</div><section className='sources'><h3>Fuentes consultadas</h3><div className='source-list'>{(s.source_urls||[]).map(u=><a className='source-link' key={u} href={u} rel='noopener noreferrer' target='_blank'><span>{host(u)}</span><small>Fuente original ↗</small></a>)}</div></section><p className='meta'>Última actualización: {s.updated_at||s.published_at||'No disponible'}</p>{s.correction_history?.length?<section className='corrections'><h3>Historial de correcciones</h3>{s.correction_history.map((c,i)=><p key={i}>{c.reason}<small>{c.created_at}</small></p>)}</section>:null}</article></main>}